"""initial_migrate: remove quantity_lent from LendingBooks

Revision ID: eeba71942792
Revises:
Create Date: 2026-04-15 19:44:47.358053

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eeba71942792"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lending_book", schema=None) as batch_op:
        batch_op.drop_column("quantity_lent")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lending_book", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quantity_lent", sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
