[default]

# =========== SYSTEM BLOCK =========== #
APP_NAME = "FlaskBiblioteca"
DEBUG = false
DEBUG_TB_ENABLED = false
DEBUG_TB_INTERCEPT_REDIRECTS = false

SERVER_NAME = "localhost:5000"
PREFERRED_URL_SCHEME = "https://"


# =========== ADMIN BLOCK ============ #
FLASK_ADMIN_TITLE = "FlaskBiblioteca - controle principal"
FLASK_ADMIN_TEMPLATE = "bootstrap4"
FLASK_ADMIN_SWATCH = "cerulean"


# =========== DATABASE BLOCK =========== #
SQLALCHEMY_DATABASE_URI = "sqlite:///biblioteca.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false


# =========== SECURITY BLOCK =========== #
PASSWORD_SCHEMES = ["pbkdf2_sha512", "md5_crypt"]


# =========== LOGIN BLOCK =========== #
LOGIN_VIEW = "auth.login"
LOGIN_MESSAGE_CATEGORY = "info"
LOGIN_REFRESH_VIEW = "accounts.reauthenticate"
LOGIN_SESSION_PROTECTION = "strong"

# =========== FORM BLOCK =========== #
WTF_CSRF_ENABLED = true


# =========== MAIL BLOCK =========== #
MAIL_SERVER = "smtp.googlemail.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
MAIL_USE_SSL = false
MAIL_SUBJECT_PREFIX = "[Flasky]"
MAIL_DEBUG = false
ROLE_PREFIX = "LB"

# =========== APPEARANCE BLOCK =========== #
# BOOTSTRAP_SERVE_LOCAL = false
# BOOTSTRAP_FORM_GROUP_CLASSES = "mb-4 authentication"

# =========== DEFAULT EXTENSIONS BLOCK =========== #
EXTENSIONS = [
    "app.backend.extensions.security:init_app",
    "app.backend.extensions.database:init_app",
    "app.backend.extensions.admin:init_app",
    "app.backend.extensions.authentication:init_app",
    "app.backend.extensions.mail:init_app",
    "app.backend.extensions.commands:init_app",
]


[development]
DEBUG = true
EXTENSIONS = [
    "dynaconf_merge_unique", # to reuse extensions list from [default]
]

[testing]
DEBUG = false
TESTING = true
SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
