[default]

# =========== SYSTEM BLOCK =========== #
APP_NAME = "FlaskBiblioteca"
DEBUG = false
DEBUG_TB_ENABLED = false
DEBUG_TB_INTERCEPT_REDIRECTS = false

SERVER_NAME = "localhost:5000"
PREFERRED_URL_SCHEME = "https://"


# =========== ADMIN BLOCK ============ #
FLASK_ADMIN_TITLE = "FlaskBiblioteca"
FLASK_ADMIN_ENDPOINT = "admin"
FLASK_ADMIN_URL = "/admin"


# =========== DATABASE BLOCK =========== #
# SQLALCHEMY_DATABASE_URI = "sqlite:///${INSTANCE_PATH}/biblioteca.db"
SQLALCHEMY_DATABASE_URI = "sqlite:///biblioteca.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false

# =========== I18N BLOCK =========== #
BABEL_DEFAULT_LOCALE = "pt-BR"
BABEL_DEFAULT_TIMEZONE = "America/Sao_Paulo"

# =========== SECURITY BLOCK =========== #
PASSWORD_SCHEMES = ["pbkdf2_sha512", "md5_crypt"]


# =========== LOGIN BLOCK =========== #
LOGIN_VIEW = "auth.login"
LOGIN_MESSAGE_CATEGORY = "info"
LOGIN_REFRESH_VIEW = "accounts.reauthenticate"
LOGIN_SESSION_PROTECTION = "strong"

# =========== FORM BLOCK =========== #
WTF_CSRF_ENABLED = true


# =========== MAIL BLOCK =========== #
MAIL_SERVER = "smtp.googlemail.com"
MAIL_PORT = 587
MAIL_USERNAME = "noreply.flasky@gmail.com"
MAIL_USE_TLS = true
MAIL_USE_SSL = false
MAIL_DEFAULT_SENDER = "Time Flasky <noreply@flasky.com>"
MAIL_SUBJECT_PREFIX = "[Flasky]"
MAIL_DEBUG = false

# =========== ROLES BLOCK =========== #
ROLES = { "admin" = "Admin", "librarian" = "Librarian" }
URL_FOR = {"admin"="admin.index", "main"="main.index"}
ROLE_PREFIX = "LIBRARIAN"

# ========== BLUEPRINTS BLOCK =========== #
BLUEPRINTS = ["src.backend.routes.main:main", "src.backend.routes.auth:auth"]
# =========== DEFAULT EXTENSIONS BLOCK =========== #
EXTENSIONS = [
    "src.backend.extensions.database:init_app",
    "src.backend.extensions.i18n:init_app",
    "src.backend.extensions.security:init_app",
    "src.backend.extensions.authentication:init_app",
    "src.backend.extensions.mail:init_app",
    "src.backend.extensions.admin.admin:init_app",
    "src.backend.extensions.commands:init_app",
]


[development]
DEBUG = true
EXTENSIONS = [
    "dynaconf_merge_unique", # to reuse extensions list from [default]
]

[testing]
DEBUG = false
TESTING = true
SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
